[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "neurite"
version = "0.2"
description = "Neural networks toolbox focused on medical image analysis."
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }
classifiers = [
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
authors = [
  { name = "Adrian V. Dalca" },
  { name = "Etienne Chollet", email = "etiennepchollet@gmail.com" },
  { name = "Malte Hoffmann" },
  { name = "Andrew Hoopes" }
]
maintainers = [
  { name = "Etienne Chollet", email = "etiennepchollet@gmail.com" }
]
dependencies = [
  "torch",
  "einops",
  "pystrum",
  "tensorflow",
]
keywords = [
  "python",
  "pytorch",
  "medical-imaging",
  "segmentation",
  "medical-image-computing",
  "nibabel",
]

[project.urls]
GitHub = "https://github.com/adalca/neurite"
PyPi = "https://pypi.org/project/neurite/0.2/"